### ISSUE TITLE
feat: Use go.mod for versioning

### ISSUE THREAD

**Issue by mbevc1** [ned1313/terrahash#10]
You could pick up Golang version from `go.mod` and instead of:
https://github.com/ned1313/terrahash/blob/17d80d5e1c9a607271b29d55ebcc2b5885797dad/.github/workflows/go-build.yml#L22

use something like:
```
go-version-file: 'go.mod'
        check-latest: true
```

**Comment by ned1313** [comment]
Great suggestion!

Resolved with #15
