### ISSUE TITLE
Local module source is broken

### ISSUE THREAD

**Issue by nikolay** [ned1313/terrahash#17]
The source for modules such as "../../../modules/xyz" is shown as just "../..".

**Comment by ned1313** [comment]
Hi @nikolay! Thanks for submitting an issue. My assumption when building the tool was that locally source modules would not be part of the module lock file. I was focusing on modules sourced from version control or a registry. Do you see a use case for locally sourced modules too?

**Comment by nikolay** [comment]
This is the most significant benefit when using Terraform Cloud with a monorepo. I built something similar in Bash and hoped to replace it with your tool.

**Comment by ned1313** [comment]
Got it! I will flag this as a feature for the next release.
